### ISSUE TITLE
fichier JPI.ajax.php

### ISSUE THREAD

**Issue by ColonelMoutarde** [jmz84/Jeedom-JPI#14]
Salut, Il faudrait passer au swith case pour le test de la variable. C'est plus rationnel.

**Comment by jmz84** [comment]
Hello, 
traité dans le commit [67c39ffa43e3b487d7c6725488af176b6cc33180](https://github.com/Jeedom-Plugins-Extra/plugin-jpi/commit/67c39ffa43e3b487d7c6725488af176b6cc33180).

Merci pour ton aide.
