### ISSUE TITLE
Vérification  et correction  de displayExeption par displayException

### ISSUE THREAD

**Issue by byackee** [jmz84/Jeedom-JPI#15]
Suite au PR https://github.com/jeedom/core/issues/971, veuillez vérifier la bonne orthographe de displayException

**Comment by jmz84** [comment]
Hello, 

[fait !](https://github.com/Jeedom-Plugins-Extra/plugin-jpi/commit/78ae937714895a9329b1262740b58c3c346325a9)

A+
