### ISSUE TITLE
rafraîchissement 

### ISSUE THREAD

**Issue by spark5960** [jmz84/Jeedom-JPI#22]
Hello

J'ai un bug sur mon jeedom avec le plugin quand je le rend visible sur mon dashboard il force l'update de la page chaque seconde environ ce qui provoque l'impossibilité d'utiliser jeedom.

(Jeedom sur RPI 3, plugin semble OK sous nextdom)

Merci

**Comment by Gis70** [comment]
Salut, ton matériel où est installé jpi est il accessible quand cela se
produit ?

**Comment by spark5960** [comment]
salut, 
non il ne l'est pas. impossible de me connecter via l'adresse ip.

**Comment by Gis70** [comment]
C'est ça le problème. Quand l'équipement n'est pas accessible ça boucle
sans cesse. (Je n'ai pas dit que c'était normal mais c'est la cause)

**Comment by spark5960** [comment]
ok.
pour information j'ai simplement décoché '' visible '' le service en lui même est resté fonctionnel correctement au moment où j'en ai eu besoin (quelques heures plus tard donc il a sûrement redémarrer sur le téléphone ?)

**Comment by spark5960** [comment]
J'ai de nouveau un problème d'affichage dans le plugi JPI.

Je ne peux rien modifier ou ajouter d'autre equipement.
Voici un screen
![image](https://user-images.githubusercontent.com/58006218/86495300-205ed600-bd79-11ea-8e84-a4c2cd0f8960.png)


Merci de l'aide

**Comment by slobberbone** [comment]
Je regarde si j'ai un soucis equivalent, je te tiens au courant @spark5960

**Comment by Gis70** [comment]
ok, problème php 7.3
