### ISSUE TITLE
Compatibilité Jeedom v4

### ISSUE THREAD

**Issue by BooleanRhapsody** [jmz84/Jeedom-JPI#32]
Bonjour,

Le plugin n'est pas compatible Jeedom v4.

Pour le rendre compatible, il faut modifier dans le fichier /JPI/desktop/php/JPI.php ligne 93 :
`foreach (object::all() as $object) {  `                                        
Par
`foreach (jeeObject::all() as $object) {`

Source :
https://community.jeedom.com/t/jpi-class-object-not-found/21052

A+

**Comment by slobberbone** [comment]
Merci, il y en avait un loupé ;)
